---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    network_mode: bridge0
    environment:
      - PUID=1029
      - PGID=100
      - TZ=America/Buenos_Aires
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/data:/data #optional

    ports:
      - 8989:8989
    restart: unless-stopped
