---
version: "2.1"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    network_mode: bridge
    environment:
      - PUID=1029
      - PGID=100
      - TZ=America/Buenos_Aires
    volumes:
      - /volume1/docker/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped
